# fly.toml app configuration file generated for grupo-mexico-backend on 2023-10-01T21:33:52-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "grupo-mexico-backend"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
